### ISSUE TITLE
Error 1.8

### ISSUE THREAD

**Issue by DenisJ9798** [Beelzebu/DamageIndicator#11]
[14:59:09 ERROR]: Could not pass event EntityRegainHealthEvent to DamageIndicator v1.3.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[stalker.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[stalker.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[stalker.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [stalker.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.heal(EntityLiving.java:672) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MobEffectList.tick(MobEffectList.java:95) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MobEffect.b(SourceFile:116) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MobEffect.tick(SourceFile:103) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.bi(EntityLiving.java:480) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:262) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:263) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1457) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:174) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:385) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [stalker.jar:]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [stalker.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [stalker.jar:]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
        at cl.mastercode.DamageIndicator.listener.DamageIndicatorListener.onEntityRegainHealth(DamageIndicatorListener.java:173) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[stalker.jar:]
        ... 26 more

**Comment by jsuarezl** [comment]
Error was fixed on [version 1.3.8](https://www.spigotmc.org/resources/55974/update?update=433314).
