### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by mitchngwen** [Beelzebu/DamageIndicator#12]
I need an update for 1.18.2.

[18:49:32] [Server thread/ERROR]: Error occurred while enabling DamageIndicator v1.3.0 (Is it up to date?)
java.lang.RuntimeException: Failed to create version specific server accessor
	at com.github.magiccheese1.damageindicator.Main.onEnable(Main.java:46) ~[DamageIndicator.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.2.jar:git-Purpur-1580]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:49:32] [Server thread/INFO]: [DamageIndicator] Disabling DamageIndicator v1.3.0

**Comment by jsuarezl** [comment]
Looks like you're a bit lost here, this issue tracker is for [Damage Indicator Reborn](https://www.spigotmc.org/resources/damage-indicator-reborn.55974/), the plugin you're having trouble with is [MagicCheese1/Damage-Indicator](https://github.com/MagicCheese1/Damage-Indicator), you should ask in their issue tracker for help.

**Comment by mitchngwen** [comment]
Thank you very much!
