### ISSUE TITLE
Error on mob hit

### ISSUE THREAD

**Issue by jj136975** [Beelzebu/DamageIndicator#6]
[17:54:13 WARN]: java.lang.NoSuchMethodException: org.bukkit.entity.ArmorStand.setCollidable(boolean)
[17:54:13 WARN]:        at java.lang.Class.getMethod(Unknown Source)
[17:54:13 WARN]:        at cl.mastercode.DamageIndicator.util.CompatUtil.is18(CompatUtil.java:47)
[17:54:13 WARN]:        at cl.mastercode.DamageIndicator.listener.DamageIndicatorListener.getDefaultArmorStand(DamageIndicatorListener.java:211)
[17:54:13 WARN]:        at cl.mastercode.DamageIndicator.listener.DamageIndicatorListener.handleArmorStand(DamageIndicatorListener.java:200)
[17:54:13 WARN]:        at cl.mastercode.DamageIndicator.listener.DamageIndicatorListener.onEntityDamageEvent(DamageIndicatorListener.java:182)
[17:54:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:54:13 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:54:13 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:54:13 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[17:54:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:54:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:54:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:54:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:54:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87)
[17:54:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553)
[17:54:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466)
[17:54:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:54:13 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:54:13 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:54:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:54:13 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by jsuarezl** [comment]
Hi, the error should be fixed in the last release
https://www.spigotmc.org/resources/55974/
